name: Build/test on MacOS
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
    test:
        runs-on: macOS-latest
        strategy:
            matrix:
                py: [
                    '2.7',
                    '3.5',
                    '3.6',
                    '3.7',
                    '3.8',
                    '3.9',
                    'pypy2',
                    'pypy3',
                ]
                architecture: ['x64']
        name: "Python: ${{ matrix.py }}"
        steps:
            - uses: actions/checkout@master
            - name: Setup python
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.py }}
                  architecture: ${{ matrix.architecture }}
            - run: pip install tox
            - name: Running tox
              run: |
                  ulimit -n 4096
                  tox -e py
