name: Build/test on Windows
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
    test:
        runs-on: windows-2019
        strategy:
            matrix:
                py: [
                    '2.7',
                    '3.5',
                    '3.6',
                    '3.7',
                    '3.8',
                    '3.9',
                ]
                architecture: ['x86', 'x64']
        name: "Python: ${{ matrix.py }} (${{ matrix.architecture }})"
        steps:
            - uses: actions/checkout@master
            - name: Setup python
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.py }}
                  architecture: ${{ matrix.architecture }}
            - run: pip install tox
            - name: Running tox
              run: tox -e py
